### ISSUE TITLE
Error thrown in query with `@skip` directive

### ISSUE THREAD

**Issue by avaly** [confuser/graphql-constraint-directive#104]
Using this package v4.0.0 (as an Envelop plugin) is throwing errors for queries containing the [`@skip` directive](https://spec.graphql.org/October2021/#sec--skip).

This query:

```graphql
query Test($skipTest: Boolean!) {
  user {
    id @skip(if: $skipTest)
  }
}
```

Throws the following error:

```
TypeError: Cannot read properties of undefined (reading 'type')
    at QueryValidationVisitor.onArgumentEnter (/app/src/node_modules/graphql-constraint-directive/lib/query-validation-visitor.js:120:54)
    at Object.enter (/app/src/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/src/node_modules/graphql/language/visitor.js:197:21)
    at validateQuery (/app/src/node_modules/graphql-constraint-directive/index.js:112:3)
    at onExecute (/app/src/node_modules/graphql-constraint-directive/index.js:148:24)
    at /app/src/node_modules/@envelop/core/cjs/orchestrator.js:348:37
    at /app/src/node_modules/@envelop/core/cjs/utils.js:116:54
    at /app/src/node_modules/graphql-helix/dist/process-request.js:182:42
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at processRequest (/app/src/node_modules/graphql-helix/dist/process-request.js:59:20)
```

**Comment by confuser** [comment]
Published as v4.1.0
