### ISSUE TITLE
Causes type error when used with another schema directive that accept arguments

### ISSUE THREAD

**Issue by akhilmhdh** [confuser/graphql-constraint-directive#145]
Hey there,

I was trying out schema directive example from this guide.

Ref: https://the-guild.dev/graphql/tools/docs/schema-directives#formatting-date-strings

But when i tried to apply this directive with `graphql-constraint-directive`, whenever I pass argument from client side, the directive throws following error.

```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'directives')",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read properties of undefined (reading 'directives')",
            "    at getDirectiveValues (/Users/akhilmhdh/Akhi/test-gql-cst/node_modules/graphql/execution/values.js:287:30)",
            "    at validateScalarTypeValue (/Users/akhilmhdh/Akhi/test-gql-cst/node_modules/graphql-constraint-directive/lib/query-validation-visitor.js:151:32)",
            "    at QueryValidationVisitor.onArgumentEnter (/Users/akhilmhdh/Akhi/test-gql-cst/node_modules/graphql-constraint-directive/lib/query-validation-visitor.js:145:7)",
            "    at Object.enter (/Users/akhilmhdh/Akhi/test-gql-cst/node_modules/graphql/utilities/TypeInfo.js:391:27)",
            "    at visit (/Users/akhilmhdh/Akhi/test-gql-cst/node_modules/graphql/language/visitor.js:197:21)",
            "    at validateQuery (/Users/akhilmhdh/Akhi/test-gql-cst/node_modules/graphql-constraint-directive/index.js:113:3)",
            "    at Object.didResolveOperation (/Users/akhilmhdh/Akhi/test-gql-cst/node_modules/graphql-constraint-directive/index.js:127:26)",
            "    at /Users/akhilmhdh/Akhi/test-gql-cst/node_modules/apollo-server-core/dist/utils/dispatcher.js:12:31",
            "    at Array.map (<anonymous>)",
            "    at Dispatcher.callTargets (/Users/akhilmhdh/Akhi/test-gql-cst/node_modules/apollo-server-core/dist/utils/dispatcher.js:9:29)"
          ]
        }
      }
    }
  ]
}
```

If i don't pass any argument towards my schema directive it works fine. This happens when i pass an argument.

Screenshot.

![Screenshot 2023-01-13 at 2 07 59 PM](https://user-images.githubusercontent.com/31166322/212275421-bae5ad1f-956a-47de-8f3c-db063d453029.png)

How to Reproduce:

<details>
<summary>Files</summary>

```js
const express = require("express");
const { ApolloServer, gql } = require("apollo-server-express");

const { makeExecutableSchema } = require("@graphql-tools/schema");
const { mapSchema, MapperKind, getDirective } = require("@graphql-tools/utils");
const {
  GraphQLList,
  GraphQLObjectType,
  GraphQLString,
  defaultFieldResolver,
} = require("graphql");
const {
  constraintDirectiveTypeDefs,
  createApolloQueryValidationPlugin,
} = require("graphql-constraint-directive");

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  directive @format(defaultFormat: String = "mmmm d, yyyy") on FIELD_DEFINITION
  type Query {
    hello: String @format
  }
`;

const formatTransformer = (schema) =>
  mapSchema(schema, {
    [MapperKind.OBJECT_FIELD](fieldConfig) {
      const dateDirective = getDirective(schema, fieldConfig, "format")?.[0];
      if (dateDirective) {
        const { resolve = defaultFieldResolver } = fieldConfig;
        const { defaultFormat } = dateDirective;

        if (!fieldConfig.args) {
          throw new Error("Unexpected Error. args should be defined.");
        }

        fieldConfig.args["format"] = {
          type: GraphQLString,
        };

        fieldConfig.type = GraphQLString;
        fieldConfig.resolve = async (
          source,
          { format, ...args },
          context,
          info
        ) => {
          const newFormat = format || defaultFormat;
          return newFormat;
        };
        return fieldConfig;
      }
    },
  });

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => "Hello world!",
  },
};

let schema = makeExecutableSchema({
  typeDefs: [typeDefs, constraintDirectiveTypeDefs],
});
schema = formatTransformer(schema);

const plugins = [createApolloQueryValidationPlugin({ schema })];

const startServer = async () => {
  const server = new ApolloServer({ schema, resolvers, plugins });
  await server.start();
  const app = express();
  server.applyMiddleware({ app });
  app.listen({ port: 3000 }, () =>
    console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`)
  );
};

startServer();

```

```json
{
  "name": "test-gql-cst",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@graphql-tools/schema": "^9.0.13",
    "@graphql-tools/utils": "^9.1.4",
    "apollo-server-express": "^3.11.1",
    "express": "^4.18.2",
    "graphql": "^16.6.0",
    "graphql-constraint-directive": "^4.1.2"
  }
}
```
<details>

**Comment by velias** [comment]
@akhilmhdh  Thanks for reporting. I have to analyze what exactly happens to patch the problem. Looks like argument added by the directive somehow breaks the code trying to find validation directive on it.
