### ISSUE TITLE
Documentation generator fails when astNode missing

### ISSUE THREAD

**Issue by velias** [confuser/graphql-constraint-directive#175]
Documentation generation fails when `astNode` is missing, for example if field has been added in code.
Exception is like:
````
TypeError: Cannot read properties of undefined (reading 'directives')
at getDirectiveValues (node_modules/graphql/execution/values.js:287:30)
at MapperKind.FIELD (node_modules/graphql-constraint-directive/index.js:150:38)
at mapFields (node_modules/@graphql-tools/utils/cjs/mapSchema.js:144:37)
at mapSchema (node_modules/@graphql-tools/utils/cjs/mapSchema.js:10:37)
at node_modules/graphql-constraint-directive/index.js:148:5
````

**Comment by velias** [comment]
I will provide PR to patch this problem
